"""
Глобальные константы проекта Foodgram.

Содержит ограничения для моделей, пагинации и фильтров.
"""

MAX_EMAIL_LENGTH = 254
MAX_USERNAME_LENGTH = 150
MAX_NAME_LENGTH = 150

MAX_TAG_NAME_LENGTH = 200
MAX_TAG_SLUG_LENGTH = 200
MAX_COLOR_LENGTH = 7

MAX_INGREDIENT_NAME_LENGTH = 200
MAX_MEASUREMENT_UNIT_LENGTH = 50

MAX_RECIPE_NAME_LENGTH = 200
MIN_COOKING_TIME = 1
MIN_AMOUNT = 1

PAGE_SIZE = 6
MAX_PAGE_SIZE = 100

TRUE_VALUE = 1
FALSE_VALUE = 0