"""Константы для моделей recipes."""

MAX_RECIPE_NAME_LENGTH = 256
MAX_TAG_NAME_LENGTH = 32
MAX_INGREDIENT_NAME_LENGTH = 128
MAX_SLUG_LENGTH = 32
MAX_MEASUREMENT_UNIT_LENGTH = 64

MIN_COOKING_TIME = 1
MAX_COOKING_TIME = 1440

MIN_INGREDIENT_AMOUNT = 1
MAX_INGREDIENT_AMOUNT = 32767

TRUE_VALUE = 1
FALSE_VALUE = 0
