# Generated by Django 4.2.7 on 2026-03-30 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'recipes',
            '0002_alter_ingredient_options_alter_recipe_options_and_more',
        ),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppingcart',
            options={
                'verbose_name': 'Список покупок',
                'verbose_name_plural': 'Список покупок',
            },
        ),
    ]
