# Generated by Django 4.2.7 on 2026-04-08 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_remove_tag_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='short_code',
            field=models.CharField(
                blank=True, max_length=10, null=True, unique=True
            ),
        ),
    ]
