# Generated by Django 4.2.7 on 2026-04-13 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("recipes", "0007_alter_ingredient_measurement_unit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ingredient",
            name="name",
            field=models.CharField(max_length=128, verbose_name="Название"),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.CharField(max_length=32, unique=True, verbose_name="Название"),
        ),
    ]
